/* algs.js — OLL & PLL case data for the trainer. Each alg is wide-move-free
 * and uses only R U F B L D, the M slice, and x/y/z rotations. Every algorithm
 * was verified against csTimer's own cube engine (setup = inverse(source), solve
 * with this alg => solved). Sourced from solvethecube.com; the dot/G-perm cases
 * were replaced with verified wide-free equivalents. Generated — do not edit by hand.
 */
(function (root) {
  'use strict';
  root.LLAlgs = {
    OLL: [
  { name: "OLL 1", alg: "R U2 R' R' F R F' U2 R' F R F'" },
  { name: "OLL 2", alg: "L F U F' U' M F U F' U' L' M'" },
  { name: "OLL 3", alg: "y' F U R U' R' F' U F R U R' U' F'" },
  { name: "OLL 4", alg: "y F U R U' R' F' U' F R U R' U' F'" },
  { name: "OLL 5", alg: "R' M U2 R U R' U R M'" },
  { name: "OLL 6", alg: "R M' U2 R' U' R U' R' M" },
  { name: "OLL 7", alg: "R M' U R' U R U2 R' M" },
  { name: "OLL 8", alg: "R' M U' R U' R' U2 R M'" },
  { name: "OLL 9", alg: "R U R' U' R' F R2 U R' U' F'" },
  { name: "OLL 10", alg: "R U R' U R' F R F' R U2 R'" },
  { name: "OLL 11", alg: "F' L' U' L U F y F R U R' U' F'" },
  { name: "OLL 12", alg: "F R U R' U' F' U F R U R' U' F'" },
  { name: "OLL 13", alg: "F U R U' R2 F' R U R U' R'" },
  { name: "OLL 14", alg: "R' F R U R' F' R y' R U' R'" },
  { name: "OLL 15", alg: "L' M' U' L M L' U' L U L' M' U L M" },
  { name: "OLL 16", alg: "R M' U R' M R U R' U' R M' U' R' M" },
  { name: "OLL 17", alg: "R U R' U R' F R F' U2 R' F R F'" },
  { name: "OLL 18", alg: "F R U R' U y' R' U2 R' F R F'" },
  { name: "OLL 19", alg: "M U R U R' U' M' R' F R F'" },
  { name: "OLL 20", alg: "M U R U R' U' M2 U R U' R' M" },
  { name: "OLL 21", alg: "R U R' U R U' R' U R U2 R'" },
  { name: "OLL 22", alg: "R U2 R2 U' R2 U' R2 U2 R" },
  { name: "OLL 23", alg: "R2 D R' U2 R D' R' U2 R'" },
  { name: "OLL 24", alg: "R M' U R' U' R' M F R F'" },
  { name: "OLL 25", alg: "F' R M' U R' U' R' M F R" },
  { name: "OLL 26", alg: "R U2 R' U' R U' R'" },
  { name: "OLL 27", alg: "R' U2 R U R' U R" },
  { name: "OLL 28", alg: "M' U' M U2 M' U' M" },
  { name: "OLL 29", alg: "R U R' U' R U' R' F' U' F R U R'" },
  { name: "OLL 30", alg: "R2 U R' B' R U' R2 U R B R'" },
  { name: "OLL 31", alg: "R' U' F U R U' R' F' R" },
  { name: "OLL 32", alg: "F U R U' F' R M' U R' U' R' M" },
  { name: "OLL 33", alg: "R U R' U' R' F R F'" },
  { name: "OLL 34", alg: "R U R' U' x D' R' U R U' D x'" },
  { name: "OLL 35", alg: "R U2 R' R' F R F' R U2 R'" },
  { name: "OLL 36", alg: "L' U' L U' L' U L U L F' L' F" },
  { name: "OLL 37", alg: "F R' F' R U R U' R'" },
  { name: "OLL 38", alg: "R U R' U R U' R' U' R' F R F'" },
  { name: "OLL 39", alg: "L F' L' U' L U F U' L'" },
  { name: "OLL 40", alg: "R' F R U R' U' F' U R" },
  { name: "OLL 41", alg: "R U R' U R U2 R' F R U R' U' F'" },
  { name: "OLL 42", alg: "R' F R F' R' F R F' R U R' U' R U R'" },
  { name: "OLL 43", alg: "F' U' L' U L F" },
  { name: "OLL 44", alg: "F U R U' R' F'" },
  { name: "OLL 45", alg: "F R U R' U' F'" },
  { name: "OLL 46", alg: "R' U' R' F R F' U R" },
  { name: "OLL 47", alg: "F' L' U' L U L' U' L U F" },
  { name: "OLL 48", alg: "F R U R' U' R U R' U' F'" },
  { name: "OLL 49", alg: "R' F R' F' R2 U2 y R' F R F'" },
  { name: "OLL 50", alg: "R' F R2 B' R2 F' R2 B R'" },
  { name: "OLL 51", alg: "F U R U' R' U R U' R' F'" },
  { name: "OLL 52", alg: "R U R' U R U' B U' B' R'" },
  { name: "OLL 53", alg: "L' M' U' L U' L' U L U' L' U2 L M" },
  { name: "OLL 54", alg: "R M' U R' U R U' R' U R U2 R' M" },
  { name: "OLL 55", alg: "R U2 R2 U' R U' R' U2 F R F'" },
  { name: "OLL 56", alg: "F R U R' U' R F' R M' U R' U' R' M" },
  { name: "OLL 57", alg: "R U R' U' M' U R U' R' M" }
    ],
    PLL: [
  { name: "PLL Aa", alg: "x z' R2 U2 R' D' R U2 R' D R' z x'" },
  { name: "PLL Ab", alg: "x R2 D2 R U R' D2 R U' R x'" },
  { name: "PLL E", alg: "R2 U R' U' y R U R' U' R U R' U' R U R' y' R U' R2" },
  { name: "PLL F", alg: "U' R' U R U' R2 F' U' F U x R U R' U' R2 x'" },
  { name: "PLL Ga", alg: "R2 U R' U R' U' R U' R2 D U' R' U R D'" },
  { name: "PLL Gb", alg: "R' U' R U D' R2 U R' U R U' R U' R2 D" },
  { name: "PLL Gc", alg: "R2 U' R U' R U R' U R2 D' U R U' R' D" },
  { name: "PLL Gd", alg: "R U R' U' D R2 U' R U' R' U R' U R2 D'" },
  { name: "PLL H", alg: "M2 U M2 U2 M2 U M2" },
  { name: "PLL Ja", alg: "L' U' L F L' U' L U L F' L2 U L U" },
  { name: "PLL Jb", alg: "R U R' F' R U R' U' R' F R2 U' R' U'" },
  { name: "PLL Na", alg: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'" },
  { name: "PLL Nb", alg: "R' U R U' R' F' U' F R U R' F R' F' R U' R" },
  { name: "PLL Ra", alg: "L U2 L' U2 L F' L' U' L U L F L2 U" },
  { name: "PLL Rb", alg: "R' U2 R U2 R' F R U R' U' R' F' R2 U'" },
  { name: "PLL T", alg: "R U R' U' R' F R2 U' R' U' R U R' F'" },
  { name: "PLL Ua", alg: "R2 U' R' U' R U R U R U' R" },
  { name: "PLL Ub", alg: "R' U R' U' R' U' R' U R U R2" },
  { name: "PLL V", alg: "R' U R' U' y R' D R' D' R2 y' R' B' R B R" },
  { name: "PLL Y", alg: "F R U' R' U' R U R' F' R U R' U' R' F R F'" },
  { name: "PLL Z", alg: "R' U' R2 U R U R' U' R U R U' R U' R' U2" }
    ]
  };
})(typeof window !== 'undefined' ? window : this);
